# Generated by Django 2.2.12 on 2024-01-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.CharField(max_length=100)),
                ('diary_contents', models.TextField()),
                ('diary_date', models.DateField(unique=True)),
                ('diary_weather', models.CharField(max_length=50)),
                ('diary_mood', models.CharField(max_length=50)),
            ],
        ),
    ]
